name:                mips-simulator-hs
version:             0.1.0.0
github:              "skyzh/mips-simulator"
license:             MIT
author:              "Alex Chi"
maintainer:          "iskyzh@gmail.com"
copyright:           "Alex Chi"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/skyzh/mips-simulator#readme>

dependencies:
- base >= 4.7 && < 5
- vector

library:
  source-dirs: src

executables:
  mips-simulator-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mips-simulator-hs

tests:
  mips-simulator-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mips-simulator-hs
    - hspec
    - QuickCheck

benchmarks:
  mips-simulator-hs-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - mips-simulator-hs
    - criterion