on: [push]

name: build

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mstksg/setup-stack@v1
      - name: setup stack
        run: stack --no-terminal --skip-ghc-check setup
      - name: build
        run: stack --no-terminal --skip-ghc-check test --only-snapshot
      - name: test
        run: stack --no-terminal --skip-ghc-check test
